<?php
/**
 * Wordpress configuration.
 *
 * @package Core
 */

/*
 * Do not edit this file. Edit the config files found in the `config/`
 * dir instead.
 *
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for
 * wp-config.php.
 */

require dirname( __DIR__ ) . '/config/application.php';
require ABSPATH . 'wp-settings.php';
